### ISSUE TITLE
Any plans to support rxjava 2.x ?

### ISSUE THREAD

**Issue by asereda** [alex-shpak/rx-jersey#1]
Hello,

First of all, thank you for this nice integration work (jersey + rxjava). 

Would it be possible to add support for [rx java 2.0](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0) as well ? 

I presume it should be a separate package / module.

Thanks.

**Comment by asereda** [comment]
In fact, I see you've updated TODO already ( [list 3h ago](https://github.com/alex-shpak/rx-jersey/commit/63591235e500349b88c2b66982e1e3544e7b7739) :) )

**Comment by alex-shpak** [comment]
Hi!

Sure, I just planned to add RxJava 2 support.
For now I think to have transitive dependencies on both versions of RxJava and two features: `RxJerseyFeature` and `ReacivexJerseyFeature` corresponding.

**Comment by asereda** [comment]
While you're at it. Perhaps support generic async return type (also) using:
-  [ListenableFuture](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/util/concurrent/ListenableFuture.html) (from Guava)
- [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) (from Java 8)
-  java standard [Future](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html)

Not everbody uses RX. 
What do you think ?

**Comment by alex-shpak** [comment]
I think I would start with RxJava 2. `CompletableFuture` is also good option. but i'm not sure if `Future` is neccesary.

**Comment by maarek** [comment]
What is the status of RxJava2 support? Complete?

**Comment by alex-shpak** [comment]
Hi!

RxJava 2 support is [implemented](/alex-shpak/rx-jersey/tree/master/rx-jersey-rxjava2) for server side, but there is some issues with client side. I think maybe to switch from jersey client to some other implementation.

So if you interested only in server then you can already use it.

**Comment by maryokhin** [comment]
@alex-shpak A good inspiration would be to looks at [Apollo](https://github.com/spotify/apollo), it returns [`CompletionStage`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html) in the client, mostly in the format `CompletionStage<Response<JacksonObject>>`.

**Comment by alex-shpak** [comment]
I will check it, thanks :)
Also there is news. new Jersey `2.26` will include RxJava 2 client implementation so there will be some movement soon.

**Comment by asereda** [comment]
Hello,

What are biggest issues currently to support RxJava2 for jersey client ? The reason I'm asking is because I like the approach of sharing interfaces between server and client in the following manner :
## Example
```java
// client definition
@Path("/resource")
interface Resource {
    @GET
     Single<String> get();
}

// server side
class ServerResource implements Resource {
     @Override
    public Single<String> get() {
      return Single.just("Hello");
    }
}

// on the client
Resource  resource = WebResourceFactory.newResource(Resource .class, target);
assertThat(resource.blockingGet()).isEqualTo("Hello");
```
This is the approach that [retrofit library](http://square.github.io/retrofit/) is using, and they do integrate nicely with rx2. However no server side support (like jersey). 

What would you recommend for our (possible common) usecase ?

**Comment by alex-shpak** [comment]
Right now there is implementation for [rxjava2 client](https://github.com/jersey/jersey/tree/master/ext/rx/rx-client-rxjava2) in Jersey v2.26 which is in beta now, when it will be released I will update client and WebResourceFactory to support it.
Here is pull request for WebResourceFactory: [#3544](https://github.com/jersey/jersey/pull/3544)
Also this pull request will be highly usefull: [#235](https://github.com/jersey/jersey/pull/235)

Regarding interfaces - that's also my target. it works now in case if resources are registered manually
```java
resourceConfig.register(ServerResource.class);
```
You can then use `@Remote` annotation or `WebResourceFactoryPatched` to create resource proxy from interface
Unfortunately it doesn't work with automatic discovery. But it will be possible to do with HK2. I'm still looking for good solution.

**Comment by asereda** [comment]
> Unfortunately it doesn't work with automatic discovery. But it will be possible to do with HK2. I'm still 
 looking for good solution.

Are you referring to the fact that `@Path` annotation can't exists on both interface and implementation (otherwise jersey complains about identical resources) ?

**Comment by alex-shpak** [comment]
Yes, I case if you put `@Path` on both class and interface.

Here is few other cases:
```
@Path("/path")
interface Resource { ... }
class ResourceImpl implements Resource { ... }

resourceConfig.packages("package.here")
```
This will not work as excepted because only interface getting registered (because it has `@Path` annotation) and on request jersey cannot instantiate it.

However this should work
```
@Path("/path")
interface Resource { ... }
class ResourceImpl implements Resource { ... }

resourceConfig.register(ResourceImpl.class)
```

**Comment by alex-shpak** [comment]
@asereda 
I pushed beta version for RxJava2 proxy client. But it not tested enough yet for production use.
Note that there was artifact names changes.

**Comment by asereda-gs** [comment]
Thanks. I will take a look and let you know.

**Comment by alex-shpak** [comment]
Please reopen issue if you got any further issue with this.
