### ISSUE TITLE
Question - Will I be able to subscribe to the Server-Side Observable from a Client-Side JavaScript libraries like Angular?

### ISSUE THREAD

**Issue by dinbtechit** [alex-shpak/rx-jersey#15]
This might be a lame/rookie question. Still new to this Rx stuff (pardon my ignorance). Trying to figure out things here.

Will I be able to subscribe to the Server-Side Observable from a Client-Side JavaScript libraries like Angular or react?

**Comment by dinbtechit** [comment]
Was able to get an answer on stackoverflow -> https://stackoverflow.com/questions/59167790/rxjava2-to-rxjs-question-will-i-be-able-to-subscribe-to-the-server-side-obse

**Comment by alex-shpak** [comment]
Hi!
Sorry for late reply.
Yes, they are correct. Jersey rest interface will serialise entire reactive object into response. So you need something like websockets or message broker.

**Comment by dinbtechit** [comment]
Thanks! I'm going with Server Sent Events.
