### ISSUE TITLE
Upload to maven central

### ISSUE THREAD

**Issue by asereda** [alex-shpak/rx-jersey#3]
Is it possible to upload artifacts to maven central ? 
In some corporate environments it is the only available (external) maven repository.

**Comment by alex-shpak** [comment]
Hi.

Yes, I will come to that somewhere soon.

**Comment by alex-shpak** [comment]
It's coming soon.
https://issues.sonatype.org/browse/OSSRH-30367

**Comment by maarek** [comment]
What is the timeline to have a release up on Maven?

**Comment by alex-shpak** [comment]
Hi!

First release has been published to maven central!
```
groupId: net.winterly.rxjersey
version: 0.8.0
```
