### ISSUE TITLE
Multiple Jersey Clients

### ISSUE THREAD

**Issue by saifally** [alex-shpak/rx-jersey#8]
I want to call multiple services which have their own auth.
This is in dropwizard 
How do I configure more than one client

**Comment by alex-shpak** [comment]
Hi!

Depending on how you want it:
- You can directly use `WebResourceFactory` from `net.winterly.rxjersey.client` to create resource proxy with configured grizzly clients
- You can make own resolver for annotation like `RemoteResolver`
- If it's only headers that have to be changed, you can have interceptor (`WriteInteceptor` that adds headers depending on target host) using single client still.

Please describe your use-case more specific :)
