### ISSUE TITLE
Mystery HTTP 500 using Completable return type in combination with response headers

### ISSUE THREAD

**Issue by kennymacleod** [alex-shpak/rx-jersey#9]
After deploying rxjersey to production in a DropWizard application, I noticed my REST endpoints that returned `Completable` suddenly started responding with HTTP 500 after a short period of operation, and only a restart would fix them, after which they would resume the 500s shortly afterwards.

I've managed to narrow it down to a simple reproducible test case, the source of which can be found at [rxjersey-loadtest](https://bitbucket.org/kmacleod/rxjersey-loadtest/src). A simple `mvn clean test` will demonstrate the bug. 

The source consists of a skeleton DropWizard application that registers a single REST resource and a `ContainerResponseFilter`. The filter adds a header to the HTTP response. 

The unit test starts up the application and hits it with 1000 sequential GET requests to the REST resource, at at request number 677 (on my machine, possibly this varies) the application craps out with an HTTP 500. The test also prints out the response headers it gets back each time, and with each subsequent response you can see the HTTP header added by my filter being duplicated. My assumption is that it hits an internal hard limit inside Jersey.

When I change the REST resource to return a vanilla (non-RxJersey) 204 `Response`, it runs fine to completion, with the single header printed each time. If I change the resource to return an empty `Observable` instead of ` `Completable`, it also fails. If I use a non-empty `Observable`, it works fine. If I remove the filter, or stop it from adding the header, it works fine.

I ran it through a debug session in my IDE, with a breakpoint inside the filter, and it looks like the `messageContext` field of the `ContainerResponseContext` is the same object each time, as though it's being recycled between requests.

I've no idea why this would only happen for `Completables` and empty `Observables`.

**Comment by alex-shpak** [comment]
HI!
Thank you for report, I will try example and come back to you.

**Comment by alex-shpak** [comment]
Localised the issue.
It's happening due to singleton response instance [here](https://github.com/alex-shpak/rx-jersey/blob/21dd7d1410a4047204c28eca6224244ea353921b/rxjava2-server/src/main/java/net/winterly/rxjersey/server/rxjava2/MaybeMethodDispatcher.java#L20)

Will publish fix

**Comment by alex-shpak** [comment]
New version is `0.10.1`

**Comment by k** [comment]
is this still an issue?

**Comment by alex-shpak** [comment]
Hi!
It's fixed in `0.10.1`

@kennymacleod Please reopen if issue still exists
